data:
  target: utils.data_loader.DataModuleFromConfig
  name: GF2
  params:
    batch_size: 4
    num_workers: 4
    collect_type: 0 # 0:default; 1 mix collect function
    train:
      GF1:
        target: data.pandata_pure.PanDataset
        params:
          operate_sys: linux
          data_root_win: D:\BaiduNetdiskDownload\PanDataSet\NBU_GF1\train
          data_root_linux: ../../dataSet/GF2_raw/NBU_GF2/train
          name: GF2
          scaledict:
            LR: 1
            REF: 4
            GT: 4
          img_range: 1023
          phase: train
          lr_size: 64
          wave_lengths: [ [450, 520,630,770 ], [ 520, 590,690,890 ] ]
    validation:
      GF1:
        target: data.pandata_pure.PanDataset
        params:
          operate_sys: linux
          data_root_linux: ../../dataSet/GF2_raw/NBU_GF2/valid
          data_root_win: ..\..\..\dataSet\NBU_GF1\valid
          name: GF2
          scaledict:
            LR: 1
            REF: 4
            GT: 4
          img_range: 1023
          phase: val
          lr_size: 64
          wave_lengths: [ [450, 520,630,770 ], [ 520, 590,690,890 ] ]
    test:
      GF1:
        target: data.pandata_pure.PanDataset
        params:
          data_root_win: ..\..\..\dataSet\NBU_GF1\test
          data_root_linux: ../../dataSet/GF2_raw/NBU_GF2/test
          operate_sys: linux
          name: GF2
          scaledict:
            LR: 1
            REF: 4
            GT: 4
          # REF_FR: 16
          img_range: 1023
          phase: val
          lr_size: 64
          wave_lengths: [ [450, 520,630,770 ], [ 520, 590,690,890 ] ]







