data:
  target: utils.data_loader.DataModuleFromConfig
  name: QB
  params:
    batch_size: 4
    num_workers: 4
    collect_type: 0 # 0:default; 1 mix collect function
    test:
      QB:
        target: data.pandata_pure_fr.PanDataset
        params:
          data_root_win: ..\..\..\dataSet\NBU_QB\test
          data_root_linux: ../../dataSet/NBU_QB/test
          operate_sys: linux
          name: QB
          scaledict:
            LR: 1
#            REF: 4
            GT: 4
            REF_FR: 16
          img_range: 2047
          phase: val
          lr_size: 64
          wave_lengths: [ [ 445, 506, 632, 757 ], [ 516,595,698,853 ] ]







